version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: meu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: minha_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db